### ISSUE TITLE
Day and night and more seasonal options. 

### ISSUE THREAD

**Issue by hobiewetzels** [117HD/RLHD#347]
Hello, 

I would like to develop a plugin that changes the brightness, saturation, skybox color and contrast settings based on your time zone. To simulate a day and night cycle. Is it possible to develop a plugin that changes these settings within 117HD? I'm kinda lost atm. Any help would be appreciated. 

If this works I would also add an option to change the seasons more frequently. Let's say every week.. Thanks in advance!

**Comment by aHooder** [comment]
At least one other person is also interested in doing this, and they already submitted an initial version of their plugin here: https://github.com/runelite/plugin-hub/pull/5334, but we think it would be best if 117 HD could expose some kind of API for other plugins to interact with, instead of other plugins directly modifying our configs, which could be confusing for users. Unfortunately we haven't figured out all of the details yet, but one idea is to communicate with the API through sending JSON messages across RuneLite's EventBus. If you're willing to help with figuring out the details, feel free to drop by #plugin-dev-chat in [our Discord](https://discord.gg/U4p6ChjgSE).

Alternatively, you could also help us finish up our own daylight cycle which there's been some work on already: https://github.com/117HD/RLHD/pull/211

**Comment by hobiewetzels** [comment]
Ah thanks for the quick reply. Makes sense. Hopefully such API will be implemented some time. I thought it would be easier, just changing a variable based on time settings... I never wrote in java or developed a plugin before, so I was looking for a noobie project, but this seems far above my skill level. Good luck with the day and night addition, hope it gets finished some day. Looks amazing.

**Comment by aHooder** [comment]
Ah okay, no worries. Hopefully we'll get around to it in not too long :slightly_smiling_face:
